// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVkLTFwUAZUupp8qWt6xAtE6daMqR6HDM',
    appId: '1:194318162262:web:e309a1138fa8b4937a5ef7',
    messagingSenderId: '194318162262',
    projectId: 'clima-flutter-91a0b',
    authDomain: 'clima-flutter-91a0b.firebaseapp.com',
    storageBucket: 'clima-flutter-91a0b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLWosaNsAfsZi3kjUS6KnrK20dQNoNKN8',
    appId: '1:194318162262:android:a70163ffb89c47037a5ef7',
    messagingSenderId: '194318162262',
    projectId: 'clima-flutter-91a0b',
    storageBucket: 'clima-flutter-91a0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQRs-Ja_UzyklYNPe4aOSX3-kMkWr1msY',
    appId: '1:194318162262:ios:bdc54f2290833d857a5ef7',
    messagingSenderId: '194318162262',
    projectId: 'clima-flutter-91a0b',
    storageBucket: 'clima-flutter-91a0b.firebasestorage.app',
    iosBundleId: 'com.example.climaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQRs-Ja_UzyklYNPe4aOSX3-kMkWr1msY',
    appId: '1:194318162262:ios:bdc54f2290833d857a5ef7',
    messagingSenderId: '194318162262',
    projectId: 'clima-flutter-91a0b',
    storageBucket: 'clima-flutter-91a0b.firebasestorage.app',
    iosBundleId: 'com.example.climaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVkLTFwUAZUupp8qWt6xAtE6daMqR6HDM',
    appId: '1:194318162262:web:a8eddf78122eb6857a5ef7',
    messagingSenderId: '194318162262',
    projectId: 'clima-flutter-91a0b',
    authDomain: 'clima-flutter-91a0b.firebaseapp.com',
    storageBucket: 'clima-flutter-91a0b.firebasestorage.app',
  );
}
